package IAT_SML_ICB.gateway;

public class Util {

	public String sql_SMS_AFT_AS400="SELECT    TMTRAN.TMSYSREF												"
			+ "						, TMTRAN.TMTXSEQ														"
			+ "						, TMTRAN.TMEFFDAT	 		TMEFFDAT									"
			+ "						, TMTRAN.TMTIMENT														"
			+ "						, TMTRAN.TMACCTNO														"
			+ "						, TMTRAN.TMTXAMT														"
			+ "						, TMTRAN.TMGLCUR														"
			+ "						, TMTRAN.TMDORC															"
			+ "						, TMTRAN.TMHOSTTXCD														"
			+ "						, TXNTYP.DESC				TXNDESC										"
			+ "						, CFCONN.CFEADD															"
			+ "						, CFMAST.CFINSC															"
			+ "						, CFMAST.CFSFLG    														"
			+ "						, TMTRAN.TMTELLID														"
			+ "						, DDMEMO.CBAL BALANCE													"
			+ "				FROM		DKUDATDEP1.TMTRAN TMTRAN												"
			+ "				JOIN		DKUPARCMN.DDPAR3 TXNTYP ON 	TXNTYP.TRANCD = TMTRAN.TMHOSTTXCD		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFACCT CFACCT ON TMTRAN.TMACCTNO	= CFACCT.CFACCN 		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFCONN CFCONN ON CFACCT.CFCIFN	= CFCONN.CFACCN   		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFMAST CFMAST ON CFACCT.CFCIFN	= CFMAST.CFCIFN  		"
			+ "				LEFT JOIN   DKUDATDEP1.DDMEMO DDMEMO ON DDMEMO.ACCTNO    = TMTRAN.TMACCTNO		"
			+ "				JOIN (																			"
			+ "						SELECT MIN (CFZSEQ) CFZSEQ, CFACCN										"
			+ "						FROM 	DKUDATCIF1.CFCONN 												"
			+ "						WHERE   CFEADC = 'HP'													"
			+ "						GROUP 	BY CFACCN														"
			+ "					 ) VCONN ON VCONN.CFACCN = CFCONN.CFACCN AND VCONN.CFZSEQ = CFCONN.CFZSEQ	"
			+ "				WHERE	TMTRAN.TMAPPTYPE	NOT IN ('G', 'L', 'X', 'T') 						"
			+ "				AND 	TMTRAN.TMHOSTTXCD 	NOT IN (302, 303, 204, 338)							"
			+ "				AND     CFACCT.CFRELA		= 'P'												"
			+ "				AND		TMTRAN.TMTELLID		= 'AFTPOST'											"
			+ "				AND		CFCONN.CFEADC 		= 'HP' 												"
			+ "				ORDER	BY 	TMTRAN.TMEFFDAT, TMTRAN.TMTIMENT";
	
	public String sql_SMS_AS400="SELECT   				 TMTRAN.TMSYSREF														"
			+ "						, TMTRAN.TMTXSEQ														"
			+ "						, TMTRAN.TMEFFDAT	 		TMEFFDAT									"
			+ "						, TMTRAN.TMTIMENT														"
			+ "						, TMTRAN.TMACCTNO														"
			+ "						, TMTRAN.TMTXAMT														"
			+ "						, TMTRAN.TMGLCUR														"
			+ "						, TMTRAN.TMDORC															"
			+ "						, TMTRAN.TMHOSTTXCD														"
			+ "						, TXNTYP.DESC				TXNDESC										"
			+ "						, CFCONN.CFEADD															"
			+ "						, CFMAST.CFINSC															"
			+ "						, CFMAST.CFSFLG    														"
			+ "						, TMTRAN.TMTELLID														"
			+ "						, DDMEMO.CBAL BALANCE													"
			+ "				FROM		DKUDATDEP1.TMTRAN TMTRAN												"
			+ "				JOIN		DKUPARCMN.DDPAR3 TXNTYP ON 	TXNTYP.TRANCD = TMTRAN.TMHOSTTXCD		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFACCT CFACCT ON TMTRAN.TMACCTNO	= CFACCT.CFACCN 		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFCONN CFCONN ON CFACCT.CFCIFN	= CFCONN.CFACCN   		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFMAST CFMAST ON CFACCT.CFCIFN	= CFMAST.CFCIFN			"
			+ "				LEFT JOIN   DKUDATDEP1.DDMEMO DDMEMO ON DDMEMO.ACCTNO    = TMTRAN.TMACCTNO		"
			+ "				LEFT JOIN (																		"
			+ "						SELECT MIN (CFZSEQ) CFZSEQ, CFACCN										"
			+ "						FROM 	DKUDATCIF1.CFCONN 												"
			+ "						WHERE   CFEADC = 'HP'													"
			+ "						GROUP 	BY CFACCN														"
			+ "					 ) VCONN ON VCONN.CFACCN = CFCONN.CFACCN AND VCONN.CFZSEQ = CFCONN.CFZSEQ	"
			+ "				WHERE	TMTRAN.TMAPPTYPE	NOT IN ('G', 'L', 'X', 'T') 						"
			+ "				AND 	TMTRAN.TMHOSTTXCD 	NOT IN (302, 303, 204, 338)							"
			+ "				AND     CFACCT.CFRELA		= 'P'												"
			+ "				AND		TMTRAN.TMTELLID		!= 'AFTPOST'										"
			+ "				AND		CFCONN.CFEADC 		= 'HP' 												"
			+ "				ORDER	BY 	TMTRAN.TMEFFDAT, TMTRAN.TMTIMENT";
	
	public String sql_sml_part1="SELECT    TMTRAN.TMSYSREF												"
			+ "						, TMTRAN.TMTXSEQ														"
			+ "						, TMTRAN.TMEFFDAT	 		TMEFFDAT									"
			+ "						, TMTRAN.TMTIMENT														"
			+ "						, TMTRAN.TMACCTNO														"
			+ "						, TMTRAN.TMTXAMT														"
			+ "						, TMTRAN.TMGLCUR														"
			+ "						, TMTRAN.TMDORC															"
			+ "						, TMTRAN.TMHOSTTXCD														"
			+ "						, TXNTYP.DESC				TXNDESC										"
			+ "						, CFCONN.CFEADD															"
			+ "						, CFMAST.CFINSC															"
			+ "						, CFMAST.CFSFLG    														"
			+ "						, TMTRAN.TMTELLID														"
			+ "						, DDMEMO.CBAL BALANCE													"
			+ "				FROM		DKUDATDEP1.TMTRAN TMTRAN												"
			+ "				JOIN		DKUPARCMN.DDPAR3 TXNTYP ON 	TXNTYP.TRANCD = TMTRAN.TMHOSTTXCD		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFACCT CFACCT ON TMTRAN.TMACCTNO	= CFACCT.CFACCN 		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFCONN CFCONN ON CFACCT.CFCIFN	= CFCONN.CFACCN   		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFMAST CFMAST ON CFACCT.CFCIFN	= CFMAST.CFCIFN  		"
			+ "				LEFT JOIN   DKUDATDEP1.DDMEMO DDMEMO ON DDMEMO.ACCTNO    = TMTRAN.TMACCTNO		"
			+ "				JOIN (																			"
			+ "						SELECT MIN (CFZSEQ) CFZSEQ, CFACCN										"
			+ "						FROM 	DKUDATCIF1.CFCONN 												"
			+ "						WHERE   CFEADC = 'HP'													"
			+ "						GROUP 	BY CFACCN														"
			+ "					 ) VCONN ON VCONN.CFACCN = CFCONN.CFACCN AND VCONN.CFZSEQ = CFCONN.CFZSEQ	"
			+ "				WHERE	TMTRAN.TMAPPTYPE	NOT IN ('G', 'L', 'X', 'T') 						"
			+ "				AND 	TMTRAN.TMHOSTTXCD 	NOT IN (302, 303, 204, 338)							"
			+ "				AND     CFACCT.CFRELA		= 'P'												"
			+ "				AND		TMTRAN.TMTELLID		= 'AFTPOST'											"
			+ "				AND		CFCONN.CFEADC 		= 'HP' 	AND 	TMTRAN.TMTXSEQ>	";
	public String sql_sml_part2="  ORDER	BY 	TMTRAN.TMEFFDAT, TMTRAN.TMTIMENT";
	
	public String newSql_1="SELECT   	TMTRAN.TMSYSREF														"
			+ "						, TMTRAN.TMTXSEQ														"
			+ "						, TMTRAN.TMEFFDAT	 											"
			+ "						, TMTRAN.TMTIMENT														"
			+ "						, TMTRAN.TMACCTNO														"
			+ "						, TMTRAN.TMTXAMT														"
			+ "						, TMTRAN.TMGLCUR														"
			+ "						, TMTRAN.TMDORC															"
			+ "						, TMTRAN.TMHOSTTXCD														"
			+ "						, TXNTYP.DESC			TXNDESC										"
			+ "						, CFCONN.CFEADD	"
			+ "						, TMTRAN.TMTELLID	"
			+ "						, DDMEMO.CBAL BALANCE													"
			+ "				FROM		DKUDATDEP1.TMTRAN TMTRAN												"
			+ "				JOIN		DKUPARCMN.DDPAR3 TXNTYP ON 	TXNTYP.TRANCD = TMTRAN.TMHOSTTXCD		"
			+ "				LEFT JOIN 	DKUDATIFC1.CFACCT CFACCT ON TMTRAN.TMACCTNO	= CFACCT.CFACCN 		"
			+ "				LEFT JOIN 	DKUDATIFC1.CFCONN CFCONN ON CFACCT.CFCIFN	= CFCONN.CFACCN   		"
			+ "				LEFT JOIN 	DKUDATCIF1.CFMAST CFMAST ON CFACCT.CFCIFN	= CFMAST.CFCIFN			"
			+ "				LEFT JOIN   DKUDATDEP1.DDMEMO DDMEMO ON DDMEMO.ACCTNO    = TMTRAN.TMACCTNO		"
			+ "				LEFT JOIN (																		"
			+ "						SELECT MIN (CFZSEQ) CFZSEQ, CFACCN										"
			+ "						FROM 	DKUDATIFC1.CFCONN 												"
			+ "						WHERE   CFEADC = 'HP'													"
			+ "						GROUP 	BY CFACCN														"
			+ "					 ) VCONN ON VCONN.CFACCN = CFCONN.CFACCN AND VCONN.CFZSEQ = CFCONN.CFZSEQ	"
			+ "				WHERE	TMTRAN.TMAPPTYPE	NOT IN ('G', 'L', 'X', 'T') 						"
			+ "				AND 	TMTRAN.TMHOSTTXCD 	NOT IN (302, 303, 204, 338)							"
			+ "				AND     CFACCT.CFRELA		= 'P'												"
			//+ "				--AND		TMTRAN.TMTELLID		!= 'AFTPOST'										"
			+ "				AND		CFCONN.CFEADC 		= 'HP' 	AND 	(TMTRAN.TMSYSREF>				";
			//+ "				AND		TMTRAN.TMEFFDAT		=  ? 												"
			//+ "				AND		TMTRAN.TMTIMENT		>  ?												"
			//+ "				ORDER	BY 	TMTRAN.TMEFFDAT, TMTRAN.TMTIMENT ";
	public String newSql_2="   ORDER	BY 	TMTRAN.TMEFFDAT, TMTRAN.TMTIMENT ";
	public Util() {
		// TODO Auto-generated constructor stub
	}

}
